### ISSUE TITLE
Cannot access parent:: when current class scope has no parent

### ISSUE THREAD

**Issue by HidayahShukor** [buruhsd/php-ipay88#1]
Hello,

I want to use ipay88 package in Laravel. However this error occur, 

**"Cannot access parent:: when current class scope has no parent"**

Do I need to write extend controller class with package, or write 'namespace'/'use' at controller's header?

**Comment by buruhsd** [comment]
can you show me your code?

**Comment by HidayahShukor** [comment]
![WhatsApp Image 2019-06-27 at 2 12 25 PM (1)](https://user-images.githubusercontent.com/48501990/60241456-e8ab8b80-98e5-11e9-92a9-bff9c6173386.jpeg)

![WhatsApp Image 2019-06-27 at 2 12 25 PM](https://user-images.githubusercontent.com/48501990/60241463-ecd7a900-98e5-11e9-8557-5158cb9b6d85.jpeg)

**Comment by HidayahShukor** [comment]
![WhatsApp Image 2019-06-27 at 2 12 25 PM (1)](https://user-images.githubusercontent.com/48501990/60241607-535cc700-98e6-11e9-986c-908886d69304.jpeg)
![WhatsApp Image 2019-06-27 at 2 12 25 PM](https://user-images.githubusercontent.com/48501990/60241610-5657b780-98e6-11e9-942b-3eb2bcc1ad6c.jpeg)

**Comment by HidayahShukor** [comment]
Is there any tutorial for configuration like service provider beside example controller provided?
